---
title: "Tutorial on yajing625pkg"
author: "Yajingli"
date: "11/10/2019"
output: html_document
vignette: >
  %\VignetteIndexEntry{Tutorial on yajing625pkg}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
#continuous

iris=as.data.frame(iris)
iris
x=iris[,1:4]
y=iris[,5]
newdata=iris[10:15,1:4]

#categorical
Titanic=as.data.frame(Titanic)
Titanic
newt=as.data.frame(Titanic[which(Titanic$Freq>0),])
newt
x=newt[,1:3]
y=newt[,4]
newdata=newt[10:14,1:3]
```

```{r}
set.seed(101)
test=data.frame(age=sample.int(30,100,replace=T),
                sex=sample(c("Female","Male"),100,replace=T),
                weight=rnorm(100,100,10),
                local=sample(c("TRUE","FALSE"),100,replace=T),
                mood=sample(c("bad","ok","excellent"),100,replace=T)
)

x=test[1:80,1:4]
y=test[1:80,5]
newdata=test[81:100,1:4]
```

```{r}
set.seed(101)
test.na=test
test.na$age[sample.int(100,10,replace = F)]=NA
test.na$sex[sample.int(100,10,replace = F)]=NA
test.na$weight[sample.int(100,10,replace = F)]=NA
test.na$local[sample.int(100,10,replace = F)]=NA
x=test.na[1:80,1:4]
y=test.na[1:80,5]
newdata=test.na[81:100,1:4]
```

```{r}
devtools::install_github("LiArAu/NaBa")
library(NaBa)
library(Rcpp)
prior=NaBa::Info_prior(x,y)
myresult_raw=predict_naBa(prior,newdata,"raw")
myresult_class=predict_naBa(prior,ppd_data,"class")
myresult_class
```

```{r}
library(e1071)
prior2=e1071::naiveBayes(x,y)
e1071result_raw=predict(prior2,newdata,"raw")
e1071result_class=predict(prior2,newdata)
e1071result_class
```

```{r}
library(naivebayes)
prior3=naivebayes::naive_bayes(x,y)
nbresult_raw=predict(prior3,newdata,"prob")
nbresult_class=predict(prior3,newdata)
```

```{r}
#Comparisons
all.equal(myresult_raw,e1071result_raw)
all.equal(myresult_class,e1071result_class)


library(microbenchmark)
library(ggplot2)

tm <- microbenchmark::microbenchmark(
NaBa::predict_naBa(prior,ppd_data,"raw"),
predict(prior2,newdata,"raw"),
predict(prior3,newdata,"prob"))
ggplot2::autoplot(tm)
```
```{r}
cppFunction('List prob_cat(int ly,CharacterVector ty,CharacterMatrix newdata,List table){
  int entry=newdata.nrow();
  int lx=newdata.ncol();
  List all_prob;

  for (int i =0; i<ly; i++){
    NumericMatrix prob_y(entry,lx);
    for (int k =0; k<lx; k++){
      NumericMatrix x_prior=table[k];
      NumericVector m=x_prior(i,_);
      for (int j =0; j<entry; j++){
        String temp=newdata(j,k);
        prob_y(j,k)=m[temp];}
      }
    String name=ty[i];
    all_prob[name]=prob_y;
  }
  return all_prob;
}')
prob_cat(3,levels(y),newdata_cat,prior$tables[prior$catvar_names])

```
