// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pdist_num
List pdist_num(NumericMatrix all_numpredictors, CharacterVector varname, CharacterVector y, CharacterVector type);
RcppExport SEXP _NaBa_pdist_num(SEXP all_numpredictorsSEXP, SEXP varnameSEXP, SEXP ySEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type all_numpredictors(all_numpredictorsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type varname(varnameSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(pdist_num(all_numpredictors, varname, y, type));
    return rcpp_result_gen;
END_RCPP
}
// timesTwo
NumericVector timesTwo(CharacterMatrix x, Function f);
RcppExport SEXP _NaBa_timesTwo(SEXP xSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x, f));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NaBa_pdist_num", (DL_FUNC) &_NaBa_pdist_num, 4},
    {"_NaBa_timesTwo", (DL_FUNC) &_NaBa_timesTwo, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_NaBa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
