# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pdist_num <- function(all_numpredictors, varname, y, type) {
    .Call('_NaBa_pdist_num', PACKAGE = 'NaBa', all_numpredictors, varname, y, type)
}

timesTwo <- function(x, f) {
    .Call('_NaBa_timesTwo', PACKAGE = 'NaBa', x, f)
}

