# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

llh_cat <- function(all_catpredictors, varname, y, laplace) {
    .Call('_NaBa_llh_cat', PACKAGE = 'NaBa', all_catpredictors, varname, y, laplace)
}

pdist_num <- function(all_numpredictors, varname, y, type) {
    .Call('_NaBa_pdist_num', PACKAGE = 'NaBa', all_numpredictors, varname, y, type)
}

prob_cat <- function(ly, ty, newdata, table) {
    .Call('_NaBa_prob_cat', PACKAGE = 'NaBa', ly, ty, newdata, table)
}

prob_num <- function(ly, ty, newdata, table) {
    .Call('_NaBa_prob_num', PACKAGE = 'NaBa', ly, ty, newdata, table)
}

